### ISSUE TITLE
Creation of pseudo saliency maps (COCO)

### ISSUE THREAD

**Issue by ai2ys** [feiyanhu/FastSal#6]
Can additional information be shared how the pseudo saliency maps for the COCO dataset got created?

Was just the trained DeepGazeII model used to create them?

Thanks

**Comment by ai2ys** [comment]
The README included in this repository says:
"In our example, we use Deepgaze II to generate pseudo saliency maps. We save the probability saliency map with central bias in numpy files. We can provide this data upon request."

What information do you need for sharing the data?

**Comment by feiyanhu** [comment]
Could you send me an email (feiyan.hu@dcu.ie) and a brief introduction about your project. I will try to find the deep gaze II maps for coco.
