### ISSUE TITLE
Image input for pretrained SalGAN teacher network?

### ISSUE THREAD

**Issue by ai2ys** [feiyanhu/FastSal#7]
As far as I saw, the SalGAN teacher network gets fed with 'BGR' image data where only the ImageNet mean values were subtracted, no further normalization using the standard deviation. Is my understanding correct?

Is there any more information on what is the appropriate input for the networks? Because from the torchvision documentation of 'vgg16' I would have assumed that the color channel order is 'RGB' and the mean and std values to apply would be the same as for the student network.

**Comment by feiyanhu** [comment]
That's right. Input format for teacher is aligned with original SalGAN input format. Teacher and student have different input format.
